version: '3.8'
services:
  php:
    depends_on:
      - mysql
    build:
      context: .
      target: builder
    restart: unless-stopped

  php2:
    depends_on:
      - mysql
    build:
      context: .
      target: builder
    restart: unless-stopped

  nginx:
    depends_on:
      - php
    build:
      context: .
      target: server
    restart: unless-stopped
    ports:
      - "8080:80"

  nginx2:
    depends_on:
      - php
    build:
      context: .
      target: server
    restart: unless-stopped
    ports:
      - "8081:80"

  mysql:
    expose:
      - 3306
    image: mysql:5.7.22
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: "mysql"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - ./mysql:/var/lib/mysql/

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
