version: '3.8'
services:
  #PHP Service
  php:
    depends_on:
      - mysql
    build:
      context: .
      target: builder
    restart: unless-stopped
  #Nginx Service
  nginx:
    depends_on:
      - php
    build:
      context: .
      target: server
    restart: unless-stopped
    ports:
      - "8080:80"
  #MySQL Service
  mysql:
    expose:
      - 3306
    image: mysql:5.7.22
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: "mysql"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - ./mysql:/var/lib/mysql/

#Volumes
volumes:
  lbdata:
    driver: local
