version: '3.8'
services:
  #PHP Service
  php:
    build:
      context: .
      dockerfile: php/Dockerfile
      args:
        user: user
        uid: 1000
  #Nginx Service
  nginx:
    build: nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./laravel:/usr/share/nginx
  #MySQL Service
  db:
    image: mysql:5.7.22
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - lbdata:/var/lib/mysql/

#Volumes
volumes:
  lbdata:
    driver: local
